FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
ARG SERVICE
COPY . .
RUN mvn -pl ${SERVICE} -am package -DskipTests && cp ${SERVICE}/target/${SERVICE}-0.0.1-SNAPSHOT.jar /tmp/app.jar

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /tmp/app.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
